### ISSUE TITLE
Modify Bearer Command should be followed by Update Bearer Request from PDN GW

### ISSUE THREAD

**Issue by killdashnine** [travelping/ergw-gtp-c-node#10]
![image002](https://user-images.githubusercontent.com/674985/28669054-d3910f76-72d2-11e7-9cf5-5e5c99e30ec6.jpg)

With the latest version from packagecloude.io we don't see the P-GW sending Update Bearer Request to the S-GW

**Comment by RoadRunnr** [comment]
It's not implemented, yet. See https://github.com/travelping/ergw/blob/master/src/pgw_s5s8.erl#L240

I don't have any plans to work on this soon. How urgently do you need this?

**Comment by killdashnine** [comment]
I think it's a pretty crucial procedure for erGW to have to be honest. In practice what happens is, is that there is no downlink established in GTP-U in the S-GW. So the ME is attached to LTE and can send packets out, but can not receive any since the downlink is not established. So when we send back packets to S-GW they are dropped and never reach the ME.

**Comment by RoadRunnr** [comment]
We did see Modify Bearer Command in our tests on live networks. So far, not executing the Update Bearer procedure had no effect on the bearers. They did remain active and we could send data in both directions.

The procedure is for modifying the QoS and ARP settings. I was under the impression that even with the wrong QoS setting the connection would still somewhat work.

Anyhow, could you share a packet capture of how such a procedure works. I don't have a sample and it would make implementing this simpler.

**Comment by killdashnine** [comment]
We have had quite some different results on various networks. On one of them for example, the bearer session got reduced to 1mbit ( I think this is a Huawei network) when no update bearer is issued. While on other networks the speed was not affected. On this specific network however the downstream bearer just drops all the packets... I think it's Ericsson.
Will see what I can do in regards to a capture.

Forgot to mention, this is initial attach procedure I see in the ULR on the HSS

**Comment by killdashnine** [comment]
I'm afraid I can't supply you with a capture due to privacy concerns of the used network :(

**Comment by RoadRunnr** [comment]
Thanks for the effort anyway. Luckily, I found a sample in our traces just a few minutes ago.

**Comment by killdashnine** [comment]
That's good news. I'd be happy to perform some production testing if needed.

**Comment by RoadRunnr** [comment]
1.14.0 is release with Update Bearer support. Could you please test if it works for you?

**Comment by killdashnine** [comment]
I will do so today, I already tried on Saturday, but the P-GW lost it's static routes after rebooting so couldn't really tell whether it is working.

**Comment by killdashnine** [comment]
Ok, just tested, we get no Update Bearer Response from S-GW. Checking this with the operator and let you know about the results.

**Comment by killdashnine** [comment]
Ok finally got some feedback:

> `"I have checked and I see indeed that our SGW is not replying with an Update Bearer Response message. We have had a similar issue for another inbound roamer in the past.
>  
> The reason our SGW drops/ignores the Update Bearer Request message is that your PGW didn’t use the correct UDP destination port in the Update Bearer Request message; Request messages are normally sent on UDP port 2123. However, in Modify Bearer Command scenario, the Update Bearer Request message is sort of a ‘response’ message and therefor your PGW should send the Update Bearer Request back to the source port that was used in the Modify Bearer Command message.`
> 
> * Our MME/SGW sends Modify Bearer Command message with (random) UDP source port 41024 and destination port 2123
> * Your PGW responds with UDP source port 2123 and destination port 2123
> * Transaction fails
> 
> Your PGW should’ve used destination port 41024 in above scenario/transaction.

**Comment by killdashnine** [comment]
Just wanted to let you know I'm available to perform any testing throughout this week.

**Comment by RoadRunnr** [comment]
I have a partial fix in https://github.com/travelping/ergw/tree/fix/context-teardown, but it's not ready for a release. Tomorrow is a national holiday, so it will Wednesday till I have something to test.

**Comment by killdashnine** [comment]
Just tested, the request got accepted by the S-GW, so all good it seems. We still have no downstream datapath on this specific network. I had hoped this would solve that issue as well, but that's not the case so it's probably unrelated. We see ICMP reply going back in GTP-U to S-GW and the network sees it as well, but it does not reach the phone.

Anyhow, thanks for patching this!
