### ISSUE TITLE
Request: upgrade to latest ergw

### ISSUE THREAD

**Issue by killdashnine** [travelping/ergw-gtp-c-node#8]
I am getting error reports for a modify bearer request:

```
** Reason for termination == 
** {function_clause,[{ggsn_gn,request_spec,3,[]},{gtp_context,validate_ies,3,[]},{gtp_context,handle_cast,2,[]}]}
```
Which I believe has been fixed already in upstream ergw

**Comment by RoadRunnr** [comment]
* On which erGW version does this happen?
* Can you provide a PCAP of the GTP request that triggered that error?

**Comment by RoadRunnr** [comment]
1.13.1 is released, docker container and debian packages should be available shortly.

**Comment by killdashnine** [comment]
With latest version the P-GW is not starting:
`2017-07-21 09:55:27 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.844.0>
    registered_name: []
    exception exit: {{{options,{secret,<<"MySecret">>}},{ergw_aaa_app,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,134}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [<0.843.0>]
    messages: [{'EXIT',<0.845.0>,normal}]
    links: [<0.843.0>,<0.654.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 121
  neighbours:`

And when commenting out the aaa part:
`Jul 21 09:58:12 pgw03 ergw-gtp-c-node[29831]: 09:58:12.488 #033[1;31m[error] CRASH REPORT Process <0.856.0> with 0 neighbours exited with reason: {{options,{dp_handler,gtp_dp_kmod,{badmatch,error},[{ergw_loader,load,3,[]},{ergw_config,validate_option,2,[]},{ergw_config,validate_options,2,[]},{ergw_config,validate_options,2,[]},{ergw_config,validate_options,4,[]},{ergw_config,load_config,1,[]},{ergw_app,'-start/2-fun-1-',1,[]}]}},{ergw_app,start,[normal,[]]}} in application_master:init/4 line 134#033[0m
Jul 21 09:58:12 pgw03 ergw-gtp-c-node[29831]: 09:58:12.489 #033[1;37m[info] Application ergw exited with reason: {{options,{dp_handler,gtp_dp_kmod,{badmatch,error},[{ergw_loader,load,3,[]},{ergw_config,validate_option,2,[]},{ergw_config,validate_options,2,[]},{ergw_config,validate_options,2,[]},{ergw_config,validate_options,4,[]},{ergw_config,load_config,1,[]},{ergw_app,'-start/2-fun-1-',1,[]}]}},{ergw_app,start,[normal,[]]}}#033[0m
Jul 21 09:58:12 pgw03 ergw-gtp-c-node[29831]: [os_mon] memory supervisor port (memsup): Erlang has closed
Jul 21 09:58:12 pgw03 ergw-gtp-c-node[29831]: [os_mon] cpu supervisor port (cpu_sup): Erlang has closed
Jul 21 09:58:14 pgw03 ergw-gtp-c-node[29831]: {"Kernel pid terminated",application_controller,"{application_start_failure,ergw,{{options,{dp_handler,gtp_dp_kmod,{badmatch,error},[{ergw_loader,load,3,[]},{ergw_config,validate_option,2,[]},{ergw_config,validate_options,2,[]},{ergw_config,validate_options,2,[]},{ergw_config,validate_options,4,[]},{ergw_config,load_config,1,[]},{ergw_app,'-start/2-fun-1-',1,[]}]}},{ergw_app,start,[normal,[]]}}}"}
Jul 21 09:58:14 pgw03 ergw-gtp-c-node[29831]: Kernel pid terminated (application_controller) ({application_start_failure,ergw,{{options,{dp_handler,gtp_dp_kmod,{badmatch,error},[{ergw_loader,load,3,[]},{ergw_config,validate_option,2,[]},{ergw_con
`

**Comment by RoadRunnr** [comment]
The old sample configuration contained an error. You need to adjust the ergw_aaa config to:

    {ergw_aaa_provider, {ergw_aaa_mock, [{shared_secret, <<"MySecret">>}]}}

I'm not sure what is causing the ergw_loader crash. Still investigating.

**Comment by killdashnine** [comment]
That did the trick indeed, just did a fresh ubuntu install, but still the same:
`2017-07-21 11:37:39.888 [error] <0.856.0> CRASH REPORT Process <0.856.0> with 0 neighbours exited with reason: {{options,{dp_handler,gtp_dp_kmod,{badmatch,error},[{ergw_loader,load,3,[]},{ergw_config,validate_option,2,[]},{ergw_config,validate_options,2,[]},{ergw_config,validate_options,2,[]},{ergw_config,validate_options,4,[]},{ergw_config,load_config,1,[]},{ergw_app,'-start/2-fun-1-',1,[]}]}},{ergw_app,start,[normal,[]]}} in application_master:init/4 line 134
`
Since it's complaining about kmod, I'm running Linux pgw04 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by killdashnine** [comment]
Getting a bit further by checking your test configs in ergw repo (added dp_handler):
` {ergw, [ {dp_handler, '$meck'},
     {sockets,
      [{irx, [{type, 'gtp-c'},
          {ip,  {XXXX}},
          {netdev, "grx"},
          freebind
         ]},
       {grx, [{type, 'gtp-u'},
          {node, 'ergw-gtp-u-node@pgw04'},
          {name, 'grx'}]}
      ]},
`
But now I am getting a different error, which I don't quite understand yet:
`Jul 21 12:00:38 pgw04 ergw-gtp-c-node[28369]: 12:00:38.357 #033[0;38m[debug] Supervisor ergw_sup started ergw:start_link() at pid <0.869.0>#033[0m
Jul 21 12:00:38 pgw04 ergw-gtp-c-node[28369]: 12:00:38.357 #033[0;38m[debug] GGSN S5/S8 Options: [{handler,pgw_s5s8},{protocol,gn},{sockets,[irx]},{data_paths,[grx]},{aaa,[{'Username',[{default,['IMSI',<<"@">>,'APN']}]}]}]#033[0m
Jul 21 12:00:38 pgw04 ergw-gtp-c-node[28369]: 12:00:38.358 #033[0;38m[debug] GGSN S5/S8 Options: [{handler,pgw_s5s8},{protocol,s5s8},{sockets,[irx]},{data_paths,[grx]}]#033[0m
Jul 21 12:00:38 pgw04 ergw-gtp-c-node[28369]: 12:00:38.358 #033[1;31m[error] CRASH REPORT Process <0.856.0> with 0 neighbours exited with reason: call to undefined function gtp_dp:validate_options([{type,'gtp-u'},{node,'ergw-gtp-u-node@pgw04'},{name,grx}]) in application_master:init/4 line 134#033[0m
Jul 21 12:00:38 pgw04 ergw-gtp-c-node[28369]: 12:00:38.359 #033[1;37m[info] Application ergw exited with reason: call to undefined function gtp_dp:validate_options([{type,'gtp-u'},{node,'ergw-gtp-u-node@pgw04'},{name,grx}])#033[0m
Jul 21 12:00:38 pgw04 ergw-gtp-c-node[28369]: [os_mon] memory supervisor port (memsup): Erlang has closed
Jul 21 12:00:38 pgw04 ergw-gtp-c-node[28369]: [os_mon] cpu supervisor port (cpu_sup): Erlang has closed
Jul 21 12:00:39 pgw04 ergw-gtp-c-node[28369]: {"Kernel pid terminated",application_controller,"{application_start_failure,ergw,{bad_return,{{ergw_app,start,[normal,[]]},{'EXIT',{undef,[{gtp_dp,validate_options,[[{type,'gtp-u'},{node,'ergw-gtp-u-node@pgw04'},{name,grx}]],[]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,273}]}]}}}}}"}
Jul 21 12:00:39 pgw04 ergw-gtp-c-node[28369]: Kernel pid terminated (application_controller) ({application_start_failure,ergw,{bad_return,{{ergw_app,start,[normal,[]]},{'EXIT',{undef,[{gtp_dp,validate_options,[[{type,'gtp-u'},{node,'ergw-gtp-u-no
Jul 21 12:00:39 pgw04 ergw-gtp-c-node[28369]: #015
Jul 21 12:00:41 pgw04 ergw-gtp-c-node[28369]: Crash dump is being written to: erl_crash.dump...done
`

**Comment by RoadRunnr** [comment]
You can't use the '$meck' handler, that's a internal shortcut for testing only.

**Comment by killdashnine** [comment]
Ok, I did find the following:
`2017-07-21 12:07:47.184 [error] <0.558.0> CRASH REPORT Process <0.558.0> with 1 neighbours exited with reason: no match of right hand value {error,2717908991} in gtp_u_kernel:init/1 line 69 in gen_server:init_it/6 line 352
`
This is gtp-**u**-node logs and it appears to happen when gtp-c-node is starting, looks like some kind of communication problem between c and u due to fault in u:
`ok = nl_simple_request(RtNl, ?NETLINK_ROUTE, CreateGTPReq),`

Looks like it can't open the netlink route in the kernel?

**Comment by RoadRunnr** [comment]
yes, but that's a different problem.

The gtp-u was unable to talk to the gtp module or got an error back from it. You should use 4.8 or later to have a current enough gtp module.

**Comment by RoadRunnr** [comment]
HiPE dependency was missing, fixed version is building right now.

**Comment by killdashnine** [comment]
My bad regarding the kernel. I will give it a go when I have upgraded the kernel

**Comment by killdashnine** [comment]
On 4.7.10-040710-generic #201611241500-Ubuntu now as std ubuntu kernels > 4.8 don't seem to support vrf... GTP kernel module seems to be ok now and both gtp-c and gtp-u are seemingly working. Will run a full pdp activation later this afternoon to see if the modify beaer request issue has been resolved. But I need some DNS updates first.

**Comment by killdashnine** [comment]
Yes, the latest ergw solved the issue with modify bearer request. Thank for fixing the new debs.
